### PR TITLE
Adds demo abstrack clock

### PR DESCRIPTION
**Pull request by castrolol**
adds a demo based in Abstract Clock (http://codepen.io/castrolol/details/PwvBNj/)

### CODE REVIEW

**Comment by meodai** [comment]
I love it thank you!  Would look event better centered on the page I think ;)

**Comment by meodai** [comment]
@castrolol this does the trick if you add autoprefixer to the codepen demo.

``` css
.clock {
  position: absolute;
  width: 550px;
  height: 550px;
  top: 50%; left: 50%;
  transform: translate(-50%,-50%)
}
```

**Comment by castrolol** [comment]
@meodai awesome... fixed! http://codepen.io/castrolol/pen/GgVXNM?editors=011

**Comment by meodai** [comment]
@castrolol I see that you did "digits.getHour().value + digits.getHour().progress" do you think it would be more useful to have the progress incorporated in the value directly `digits.getHour().value //11.23` or event a third value? @caillou had a similar idea I think

**Comment by castrolol** [comment]
@meodai Maybe a thirdy property like fullValue or similar

**Pull request merged**
